services:
  herald:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herald-server
    environment:
      HERALD_ENV: docker
    volumes:
      - ./config.json:/app/config.json:ro
      - ./config.docker.json:/app/config.docker.json:ro
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - herald

networks:
  herald:
    name: herald
    driver: bridge
